context.properties = {
    ## Set the base rate
    default.clock.rate          = 48000

    ## Allow switching to match source material
    ## Most HDMI outputs support up to 192kHz
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]

    ## Use the highest quality resampler
    ## 10 provides professional grade transparency
    resample.quality            = 10
}

